export const GET_POKEMON_LOADING = 'GET_POKEMON_LOADING';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAIL = 'GET_POKEMON_FAIL';
export const CLEAR_MSG_ERROR = 'CLEAR_MSG_ERROR';
export const LOAD_POKEMON_FIREBASE = 'LOAD_POKEMON_FIREBASE';
export const CREATE_POKEMON_FIREBASE = 'CREATE_POKEMON_FIREBASE';
export const DELETE_POKEMON_FIREBASE = 'DELETE_POKEMON_FIREBASE';
